name: Build Debug APK

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Build
      run: |
        cd IEMS5725_Classroom
        chmod +x ./gradlew
        ./gradlew assembleRelease
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: IEMS5725_Classroom/app/build/outputs/apk/release/app-release-unsigned.apk
      
